### ISSUE TITLE
Take this down

### ISSUE THREAD

**Issue by SmallPP420** [Autist69420/rust-r34-scraper#1]
Haram bro

It's haram

![image](https://user-images.githubusercontent.com/78730004/162791212-3e196d35-aed9-481d-a97b-e8f58c0d8657.png)

**Comment by Autist69420** [comment]
no, fuck you fr0g

**Comment by SmallPP420** [comment]
Kill yourself

**Comment by SmallPP420** [comment]
![IMG-20220411-WA0000](https://user-images.githubusercontent.com/78730004/162791743-c14ab8f5-0710-4337-9dda-ec033f893f5e.jpg)

**Comment by SmallPP420** [comment]
I'm joking
