### ISSUE TITLE
Error: Error("invalid type: map, expected a sequence", line: 1, column: 0)

### ISSUE THREAD

**Issue by Zer0dev-byte** [Autist69420/rust-r34-scraper#3]
So um I get this error when I try to run the demo code so it would be very much appreciated if I could get help
`./target/debug/rust-r34-scraper --site rule34.xxx --limit 100 --tags "nude sex video" --dir ./
---------------------------------------
| URL: rule34.xxx
| Limit: 100
| Tags: nude sex video
---------------------------------------
Started Scraping like the horny bitch you are
Error: Error("invalid type: map, expected a sequence", line: 1, column: 0)`

**Comment by Autist69420** [comment]
I don't provide support for this. I made this for myself to use and just put it on github for archival purposes. You're on your own.
