### ISSUE TITLE
Error: Error("invalid type: map, expected a sequence", line: 1, column: 0)

### ISSUE THREAD

**Issue by modpotato** [Autist69420/rust-r34-scraper#4]
running causes this issue

**Comment by modpotato** [comment]
![image](https://user-images.githubusercontent.com/81768237/210182801-2fb61553-2897-4bcd-a5ce-673d5e9cd661.png)

**Comment by Autist69420** [comment]
https://github.com/Autist69420/rust-r34-scraper/issues/3#issuecomment-1355897712 read this, fix it yourself. archiving this entire project now
